# Generated by Django 4.1.2 on 2022-10-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_product_wishlist_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
