# Generated by Django 4.1.2 on 2022-10-13 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
