# Generated by Django 4.1.2 on 2022-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='image', upload_to='contacts/%Y/%M/%d'),
            preserve_default=False,
        ),
    ]
